"""
LangGraph claims analysis agent.

Workflow:
  fetch_claims → parse_and_score → call_claude_insights → rank_campaigns → format_output

Produces ROI-ranked preventive campaigns with economic justification generated by Claude.
The scoring engine runs first so Claude receives pre-analyzed patterns, not raw CPT codes.
"""

from __future__ import annotations

import json
import logging
from typing import Any, TypedDict

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import END, StateGraph

from src.backend.scoring.claims_analyzer import analyze_claims, ClaimsAnalysis
from src.backend.scoring.risk_calculator import calculate_risk
from src.backend.database.queries import (
    get_member,
    get_member_claims,
    save_audit_log,
)

logger = logging.getLogger(__name__)

CLAIMS_SYSTEM_PROMPT = """You are a population health analyst for a health insurance plan.
You receive pre-analyzed claims data (patterns, cost drivers, care gaps) for a specific member
and generate actionable preventive health campaigns with ROI justification.

TASK: Generate 3-5 campaigns, each targeting a specific gap or risk pattern identified in the data.
Campaigns should be:
1. Clinically grounded (reference the specific ICD-10 or CPT evidence)
2. ROI-positive (show the math: intervention cost vs. avoided event cost)
3. Actionable (specific outreach message, timing, channel)
4. Ranked by total ROI and urgency

Return JSON array with this structure:
[
  {
    "campaign_id": "C001",
    "title": "<short campaign name>",
    "target_gap": "<what gap this addresses>",
    "intervention": "<specific action>",
    "outreach_channel": "phone | sms | portal | mail",
    "timing": "<when to reach out>",
    "clinical_rationale": "<1-2 sentences citing evidence>",
    "projected_annual_savings": <number>,
    "intervention_cost": <number>,
    "roi_multiple": <savings/cost as float>,
    "urgency": "critical | high | medium | low",
    "icd10_codes": ["<codes>"]
  }
]"""


class ClaimsState(TypedDict):
    member_id: str

    # DB data
    member: dict | None
    raw_claims: list[dict]

    # Analysis results
    analysis: ClaimsAnalysis | None
    risk_score: dict | None

    # Claude output
    raw_claude_output: str
    campaigns: list[dict]

    # Final
    patterns_found: list[str]
    projected_savings: float
    roi_analysis: dict
    error: str | None


def _fetch_claims_node(state: ClaimsState) -> ClaimsState:
    """Node 1: Fetch member and full claims history."""
    member_id = state["member_id"]
    member = get_member(member_id) or {}
    claims = get_member_claims(member_id, limit=100)

    if not claims:
        logger.warning(f"No claims found for {member_id} — proceeding with empty set")

    return {**state, "member": member, "raw_claims": claims}


def _parse_and_score_node(state: ClaimsState) -> ClaimsState:
    """Node 2: Run claims analyzer and risk calculator."""
    member = state.get("member") or {}
    claims = state.get("raw_claims", [])
    member_id = state["member_id"]

    analysis = analyze_claims(member_id, claims)

    risk = calculate_risk(
        member_id=member_id,
        age=member.get("age", 45),
        conditions=member.get("conditions", []),
        medications=member.get("medications", []),
        claims=claims,
        social_risk_flags=member.get("social_risk_flags", []),
    )

    patterns = [p.description for p in analysis.patterns]

    return {
        **state,
        "analysis": analysis,
        "risk_score": {
            "overall_risk": risk.overall_risk,
            "tier": risk.tier,
            "predicted_annual_cost": risk.predicted_annual_cost,
        },
        "patterns_found": patterns,
    }


def _call_claude_insights_node(state: ClaimsState) -> ClaimsState:
    """Node 3: Claude generates campaign narratives from structured analysis."""
    if state.get("error"):
        return state

    from src.backend.config import settings

    analysis: ClaimsAnalysis = state["analysis"]
    member = state.get("member") or {}
    risk = state.get("risk_score") or {}

    # Build structured summary for Claude
    cost_drivers_text = "\n".join(
        f"  - {d.category}: ${d.total_cost:,.0f} ({d.claim_count} claims)"
        for d in analysis.cost_drivers[:5]
    )

    patterns_text = "\n".join(
        f"  - [{p.severity.upper()}] {p.description}"
        for p in analysis.patterns
    )

    gaps_text = "\n".join(
        f"  - {g.screening_type}: last done {g.last_performed or 'never'}, "
        f"saves ~${g.estimated_savings:,.0f}/year"
        for g in analysis.prevention_gaps
    )

    user_content = f"""Member Analysis:
- Member ID: {state['member_id']}
- Age: {member.get('age', 'unknown')}
- Conditions: {', '.join(member.get('conditions', [])) or 'None'}
- Risk tier: {risk.get('tier', 'unknown')} ({risk.get('overall_risk', 'N/A')}/100)
- Predicted annual cost: ${risk.get('predicted_annual_cost', 0):,.0f}
- Total claims cost (period): ${analysis.total_cost:,.0f} across {analysis.claim_count} claims
- ER visits: {analysis.er_visit_count}
- Hospitalizations: {analysis.hospitalization_count}
- Chronic conditions identified: {', '.join(analysis.chronic_conditions) or 'None'}

Top Cost Drivers:
{cost_drivers_text or '  (none)'}

Detected Care Patterns:
{patterns_text or '  (none)'}

Preventive Gaps:
{gaps_text or '  (none)'}

Generate 3-5 targeted preventive campaigns with ROI justification. Return as JSON array."""

    try:
        llm = ChatAnthropic(
            model="claude-opus-4-7",
            api_key=settings.anthropic_api_key,
            temperature=0.3,
        )
        response = llm.invoke([
            SystemMessage(content=CLAIMS_SYSTEM_PROMPT),
            HumanMessage(content=user_content),
        ])
        raw = response.content if isinstance(response.content, str) else str(response.content)
        return {**state, "raw_claude_output": raw}

    except Exception as exc:
        logger.error(f"Claude claims call failed: {exc}")
        return {**state, "error": f"AI service error: {str(exc)[:100]}"}


def _rank_campaigns_node(state: ClaimsState) -> ClaimsState:
    """Node 4: Parse Claude campaigns, augment with scoring engine data, rank by ROI."""
    if state.get("error"):
        return state

    raw = state.get("raw_claude_output", "")
    campaigns: list[dict] = []

    try:
        import re
        match = re.search(r"\[[\s\S]*\]", raw)
        if match:
            campaigns = json.loads(match.group())
    except (json.JSONDecodeError, AttributeError):
        logger.warning("Failed to parse campaigns JSON")

    # Augment with prevention gap data from the scoring engine
    analysis: ClaimsAnalysis = state["analysis"]
    if not campaigns and analysis.prevention_gaps:
        # Fallback: generate basic campaigns from scoring engine gaps
        for i, gap in enumerate(analysis.prevention_gaps[:4]):
            campaigns.append({
                "campaign_id": f"C{str(i + 1).zfill(3)}",
                "title": f"{gap.screening_type} Outreach",
                "target_gap": gap.screening_type,
                "intervention": f"Schedule {gap.screening_type}",
                "outreach_channel": "phone",
                "timing": "Within 30 days",
                "clinical_rationale": f"Screening overdue. ICD-10: {gap.icd10_for_gap}",
                "projected_annual_savings": gap.estimated_savings,
                "intervention_cost": 150,
                "roi_multiple": round(gap.estimated_savings / 150, 1),
                "urgency": "high",
                "icd10_codes": [gap.icd10_for_gap],
            })

    # Sort by ROI multiple descending
    campaigns.sort(key=lambda c: float(c.get("roi_multiple", 0)), reverse=True)

    total_savings = sum(float(c.get("projected_annual_savings", 0)) for c in campaigns)
    total_cost = sum(float(c.get("intervention_cost", 0)) for c in campaigns)

    roi_analysis = {
        "campaign_count": len(campaigns),
        "total_projected_savings": round(total_savings, 2),
        "total_intervention_cost": round(total_cost, 2),
        "portfolio_roi_multiple": round(total_savings / total_cost, 1) if total_cost > 0 else 0,
        "top_opportunity": campaigns[0]["title"] if campaigns else None,
    }

    try:
        save_audit_log(
            action="claims_analysis",
            user_id=state["member_id"],
            resource="claims_agent",
            details={"campaigns_generated": len(campaigns), "total_savings": total_savings},
        )
    except Exception:
        pass

    return {
        **state,
        "campaigns": campaigns,
        "projected_savings": total_savings,
        "roi_analysis": roi_analysis,
    }


def _build_claims_graph() -> Any:
    graph = StateGraph(ClaimsState)

    graph.add_node("fetch_claims", _fetch_claims_node)
    graph.add_node("parse_and_score", _parse_and_score_node)
    graph.add_node("call_claude_insights", _call_claude_insights_node)
    graph.add_node("rank_campaigns", _rank_campaigns_node)

    graph.set_entry_point("fetch_claims")
    graph.add_edge("fetch_claims", "parse_and_score")
    graph.add_edge("parse_and_score", "call_claude_insights")
    graph.add_edge("call_claude_insights", "rank_campaigns")
    graph.add_edge("rank_campaigns", END)

    return graph.compile()


claims_graph = _build_claims_graph()


def run_claims_analysis(member_id: str) -> dict:
    """
    Entry point for claims agent.
    Returns dict with: campaigns, patterns_found, projected_savings, roi_analysis, error
    """
    initial_state: ClaimsState = {
        "member_id": member_id,
        "member": None,
        "raw_claims": [],
        "analysis": None,
        "risk_score": None,
        "raw_claude_output": "",
        "campaigns": [],
        "patterns_found": [],
        "projected_savings": 0.0,
        "roi_analysis": {},
        "error": None,
    }

    final = claims_graph.invoke(initial_state)

    if final.get("error"):
        return {"error": final["error"], "campaigns": [], "patterns_found": [], "projected_savings": 0, "roi_analysis": {}}

    return {
        "campaigns": final["campaigns"],
        "patterns_found": final["patterns_found"],
        "projected_savings": final["projected_savings"],
        "roi_analysis": final["roi_analysis"],
        "risk_score": final.get("risk_score"),
        "error": None,
    }
